name: Build CLI Tool
on:
  push:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build for linux amd64
        run: go build -o changelog main.go cli.go 
      - name: Build for windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o changelog.exe main.go cli.go
      - name: Build for mac amd64
        run: GOOS=darwin GOARCH=amd64 go build -o changelog-darwin main.go cli.go