name: Build CLI Tool
on:
  push:
    branches: [master]

jobs:
  build-linux-amd64: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build for linux amd64
        run: go build -o changelog main.go cli.go 
      - name: Create artifact directory
        run: |
          mkdir release-linux-amd64
          mv changelog release-linux-amd64/changelog
          mv .env.example release-linux-amd64/.env
          mv template.tmpl release-linux-amd64/template.tmpl
      - name: Archive release directory
        uses: actions/upload-artifact@v2
        with:
          name: release-linux
          path: release-linux-amd64