name: Build and Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux-amd64: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build for linux amd64
        run: |
          go build -o changelog main.go cli.go 
      - name: Create artifact directory
        run: |
          mkdir bin
          mv changelog template.tmpl bin/changelog
          mv .env.example release-linux-amd64/.env
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release Linux-${{ github.ref }}
          draft: false
          prerelease: false
  build-windows-amd64: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build for linux amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o changelog main.go cli.go
      - name: Create artifact directory
        run: |
          mkdir bin
          mv changelog template.tmpl bin/changelog
          mv .env.example release-linux-amd64/.env
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release Windows-${{ github.ref }}
          draft: false
          prerelease: false
  build-darwin-amd64: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build for linux amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o changelog main.go cli.go
      - name: Create artifact directory
        run: |
          mkdir bin
          mv changelog template.tmpl bin/changelog
          mv .env.example release-linux-amd64/.env
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release Darwin-${{ github.ref }}
          draft: false
          prerelease: false